services:
  web:
    container_name: azuracast
    image: "ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}"
    labels:
      - "com.centurylinklabs.watchtower.scope=azuracast"
    ports:
      - '${AZURACAST_HTTP_PORT:-80}:${AZURACAST_HTTP_PORT:-80}'
      - '${AZURACAST_HTTPS_PORT:-443}:${AZURACAST_HTTPS_PORT:-443}'
      - '${AZURACAST_SFTP_PORT:-2022}:${AZURACAST_SFTP_PORT:-2022}'
      - '${AZURACAST_STATION_PORT:-8000}:${AZURACAST_STATION_PORT:-8000}'
    volumes:
      - /home/container:/var/azuracast
      - /home/container/db:/var/lib/mysql
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "5"
  updater:
    container_name: azuracast_updater
    image: ghcr.io/azuracast/updater:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "1m"
        max-file: "5"
